/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;
import java.awt.Graphics2D;
import java.awt.*;
/**
 *
 * @author yenson
 */
/**
 *Clase principal de la interfaz
 */
public class InterfazDots extends javax.swing.JFrame {

    /**
     * Creates new form InterfazDots
     */
    public InterfazDots() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void linea (int x1, int x2, int y1, int y2){
    
        Graphics2D l = (Graphics2D)jLineas.getGraphics();
        BasicStroke Sl = new BasicStroke(9.0f, BasicStroke.CAP_SQUARE, BasicStroke.CAP_SQUARE);
        l.setStroke(Sl);
        l.setPaint(Color.BLUE);
        l.drawLine(x1, x2, y1, y2);

    }
    public void relleno (int x[], int y[], int n){
        Graphics2D r = (Graphics2D)jLineas.getGraphics();
        BasicStroke Sr = new BasicStroke(9.0f, BasicStroke.CAP_SQUARE, BasicStroke.CAP_SQUARE);
        r.setStroke(Sr);
        r.setPaint(Color.RED);
        r.fillPolygon(x, y, n);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jExit = new javax.swing.JButton();
        jContinuar = new javax.swing.JButton();
        A1 = new javax.swing.JButton();
        A2 = new javax.swing.JButton();
        A3 = new javax.swing.JButton();
        A4 = new javax.swing.JButton();
        A5 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        C1 = new javax.swing.JButton();
        C2 = new javax.swing.JButton();
        C3 = new javax.swing.JButton();
        C4 = new javax.swing.JButton();
        C5 = new javax.swing.JButton();
        D1 = new javax.swing.JButton();
        D2 = new javax.swing.JButton();
        D3 = new javax.swing.JButton();
        D4 = new javax.swing.JButton();
        D5 = new javax.swing.JButton();
        E1 = new javax.swing.JButton();
        E2 = new javax.swing.JButton();
        E3 = new javax.swing.JButton();
        E4 = new javax.swing.JButton();
        E5 = new javax.swing.JButton();
        F1 = new javax.swing.JButton();
        F2 = new javax.swing.JButton();
        F3 = new javax.swing.JButton();
        F4 = new javax.swing.JButton();
        F5 = new javax.swing.JButton();
        jLineas = new javax.swing.JPanel();
        jDOTS = new javax.swing.JLabel();
        jBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.darkGray);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jExit.setBackground(new java.awt.Color(254, 254, 254));
        jExit.setForeground(new java.awt.Color(80, 80, 80));
        jExit.setText("Salir");
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });
        getContentPane().add(jExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 80, -1));

        jContinuar.setBackground(new java.awt.Color(254, 254, 254));
        jContinuar.setForeground(new java.awt.Color(85, 85, 85));
        jContinuar.setText("Continuar");
        jContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(jContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        A1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        A1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A1.setBorderPainted(false);
        A1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A1MouseClicked(evt);
            }
        });
        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });
        getContentPane().add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        A2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        A2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A2.setBorderPainted(false);
        A2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A2MouseClicked(evt);
            }
        });
        A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2ActionPerformed(evt);
            }
        });
        getContentPane().add(A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        A3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        A3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A3.setBorderPainted(false);
        A3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A3MouseClicked(evt);
            }
        });
        A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3ActionPerformed(evt);
            }
        });
        getContentPane().add(A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        A4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        A4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A4.setBorderPainted(false);
        A4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A4MouseClicked(evt);
            }
        });
        A4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A4ActionPerformed(evt);
            }
        });
        getContentPane().add(A4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        A5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        A5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A5.setBorderPainted(false);
        A5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A5MouseClicked(evt);
            }
        });
        A5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A5ActionPerformed(evt);
            }
        });
        getContentPane().add(A5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, -1, -1));

        B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        B1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B1.setBorderPainted(false);
        B1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B1MouseClicked(evt);
            }
        });
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        getContentPane().add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        B2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B2.setBorderPainted(false);
        B2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B2MouseClicked(evt);
            }
        });
        getContentPane().add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        B3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        B3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B3.setBorderPainted(false);
        B3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B3MouseClicked(evt);
            }
        });
        getContentPane().add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        B4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        B4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B4.setBorderPainted(false);
        B4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B4MouseClicked(evt);
            }
        });
        getContentPane().add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));

        B5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        B5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B5.setBorderPainted(false);
        B5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B5MouseClicked(evt);
            }
        });
        getContentPane().add(B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, -1, -1));

        C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        C1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C1.setBorderPainted(false);
        C1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C1MouseClicked(evt);
            }
        });
        C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1ActionPerformed(evt);
            }
        });
        getContentPane().add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        C2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C2.setBorderPainted(false);
        C2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C2MouseClicked(evt);
            }
        });
        getContentPane().add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        C3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        C3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C3.setBorderPainted(false);
        C3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C3MouseClicked(evt);
            }
        });
        getContentPane().add(C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        C4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        C4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C4.setBorderPainted(false);
        C4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C4MouseClicked(evt);
            }
        });
        getContentPane().add(C4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, -1));

        C5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        C5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C5.setBorderPainted(false);
        C5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C5MouseClicked(evt);
            }
        });
        getContentPane().add(C5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, -1));

        D1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        D1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D1.setBorderPainted(false);
        D1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D1MouseClicked(evt);
            }
        });
        D1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D1ActionPerformed(evt);
            }
        });
        getContentPane().add(D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        D2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        D2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D2.setBorderPainted(false);
        D2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D2MouseClicked(evt);
            }
        });
        getContentPane().add(D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, -1));

        D3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        D3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D3.setBorderPainted(false);
        D3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D3MouseClicked(evt);
            }
        });
        getContentPane().add(D3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, -1, -1));

        D4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        D4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D4.setBorderPainted(false);
        D4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D4MouseClicked(evt);
            }
        });
        getContentPane().add(D4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, -1, -1));

        D5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        D5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D5.setBorderPainted(false);
        D5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D5MouseClicked(evt);
            }
        });
        getContentPane().add(D5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, -1, -1));

        E1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        E1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        E1.setBorderPainted(false);
        E1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E1MouseClicked(evt);
            }
        });
        E1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1ActionPerformed(evt);
            }
        });
        getContentPane().add(E1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, -1, -1));

        E2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        E2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        E2.setBorderPainted(false);
        E2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E2MouseClicked(evt);
            }
        });
        getContentPane().add(E2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, -1, -1));

        E3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        E3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        E3.setBorderPainted(false);
        E3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E3MouseClicked(evt);
            }
        });
        getContentPane().add(E3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, -1, -1));

        E4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        E4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        E4.setBorderPainted(false);
        E4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E4MouseClicked(evt);
            }
        });
        getContentPane().add(E4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, -1, -1));

        E5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        E5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        E5.setBorderPainted(false);
        E5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E5MouseClicked(evt);
            }
        });
        getContentPane().add(E5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 530, -1, -1));

        F1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        F1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        F1.setBorderPainted(false);
        F1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F1MouseClicked(evt);
            }
        });
        F1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F1ActionPerformed(evt);
            }
        });
        getContentPane().add(F1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, -1, -1));

        F2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        F2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        F2.setBorderPainted(false);
        F2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F2MouseClicked(evt);
            }
        });
        getContentPane().add(F2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 640, -1, -1));

        F3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        F3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        F3.setBorderPainted(false);
        F3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F3MouseClicked(evt);
            }
        });
        getContentPane().add(F3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 640, -1, -1));

        F4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        F4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        F4.setBorderPainted(false);
        F4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F4MouseClicked(evt);
            }
        });
        getContentPane().add(F4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 640, -1, -1));

        F5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        F5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        F5.setBorderPainted(false);
        F5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        getContentPane().add(F5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 640, -1, -1));

        jLineas.setOpaque(false);
        getContentPane().add(jLineas, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, 510, 690));

        jDOTS.setBackground(new java.awt.Color(252, 249, 246));
        jDOTS.setFont(new java.awt.Font("aakar", 1, 50)); // NOI18N
        jDOTS.setForeground(new java.awt.Color(72, 72, 72));
        jDOTS.setText("DOTS");
        getContentPane().add(jDOTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, -1));

        jBG.setBackground(new java.awt.Color(76, 76, 76));
        jBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bg_1.jpg"))); // NOI18N
        getContentPane().add(jBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jExitActionPerformed

    private void A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A3ActionPerformed

    private void A4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A4ActionPerformed

    private void A5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A5ActionPerformed

    private void A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2ActionPerformed

    }//GEN-LAST:event_A2ActionPerformed

    private void A2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A2MouseClicked

    }//GEN-LAST:event_A2MouseClicked

    private void A3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A3MouseClicked

    }//GEN-LAST:event_A3MouseClicked

    private void A4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A4MouseClicked

    }//GEN-LAST:event_A4MouseClicked

    private void A5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A5MouseClicked

    }//GEN-LAST:event_A5MouseClicked

    private void B1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1MouseClicked

    }//GEN-LAST:event_B1MouseClicked

    private void B2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2MouseClicked

    }//GEN-LAST:event_B2MouseClicked

    private void B3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B3MouseClicked

    }//GEN-LAST:event_B3MouseClicked

    private void B4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B4MouseClicked

    }//GEN-LAST:event_B4MouseClicked

    private void B5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B5MouseClicked

    }//GEN-LAST:event_B5MouseClicked

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B1ActionPerformed

    private void C1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C1MouseClicked

    }//GEN-LAST:event_C1MouseClicked

    private void C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C1ActionPerformed

    private void C2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C2MouseClicked

    }//GEN-LAST:event_C2MouseClicked

    private void C3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C3MouseClicked

    }//GEN-LAST:event_C3MouseClicked

    private void C4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C4MouseClicked

    }//GEN-LAST:event_C4MouseClicked

    private void C5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C5MouseClicked

    }//GEN-LAST:event_C5MouseClicked

    private void D1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D1MouseClicked

    }//GEN-LAST:event_D1MouseClicked

    private void D1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D1ActionPerformed

    private void D2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D2MouseClicked

    }//GEN-LAST:event_D2MouseClicked

    private void D3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D3MouseClicked

    }//GEN-LAST:event_D3MouseClicked

    private void D4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D4MouseClicked

    }//GEN-LAST:event_D4MouseClicked

    private void D5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D5MouseClicked

    }//GEN-LAST:event_D5MouseClicked

    private void E1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E1MouseClicked

    }//GEN-LAST:event_E1MouseClicked

    private void E1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E1ActionPerformed

    private void E2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E2MouseClicked

    }//GEN-LAST:event_E2MouseClicked

    private void E3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E3MouseClicked

    }//GEN-LAST:event_E3MouseClicked

    private void E4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E4MouseClicked

    }//GEN-LAST:event_E4MouseClicked

    private void E5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E5MouseClicked

    }//GEN-LAST:event_E5MouseClicked

    private void F1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F1MouseClicked

    }//GEN-LAST:event_F1MouseClicked

    private void F1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F1ActionPerformed

    private void F2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F2MouseClicked

    }//GEN-LAST:event_F2MouseClicked

    private void F3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F3MouseClicked

    }//GEN-LAST:event_F3MouseClicked

    private void F4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F4MouseClicked

    }//GEN-LAST:event_F4MouseClicked

    private void F5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F5MouseClicked
       
    }//GEN-LAST:event_F5MouseClicked

    private void A1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A1MouseClicked
    int a[] = { A1.getX(), A2.getX(), B3.getX(), C2.getX(), C1.getX()};
    int b[] = { A1.getY(), A2.getY(), B3.getY(), C2.getY(), C1.getY()};
        relleno(a,b,5);
    }//GEN-LAST:event_A1MouseClicked

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed

    }//GEN-LAST:event_A1ActionPerformed

    private void jContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jContinuarActionPerformed
    // Enviar los datos al servidor
        
    }//GEN-LAST:event_jContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazDots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazDots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazDots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazDots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InterfazDots Interfaz = new InterfazDots();
                Interfaz.setVisible(true);
                
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton A1;
    protected javax.swing.JButton A2;
    protected javax.swing.JButton A3;
    protected javax.swing.JButton A4;
    protected javax.swing.JButton A5;
    protected javax.swing.JButton B1;
    protected javax.swing.JButton B2;
    protected javax.swing.JButton B3;
    protected javax.swing.JButton B4;
    protected javax.swing.JButton B5;
    protected javax.swing.JButton C1;
    protected javax.swing.JButton C2;
    protected javax.swing.JButton C3;
    protected javax.swing.JButton C4;
    protected javax.swing.JButton C5;
    protected javax.swing.JButton D1;
    protected javax.swing.JButton D2;
    protected javax.swing.JButton D3;
    protected javax.swing.JButton D4;
    protected javax.swing.JButton D5;
    protected javax.swing.JButton E1;
    protected javax.swing.JButton E2;
    protected javax.swing.JButton E3;
    protected javax.swing.JButton E4;
    protected javax.swing.JButton E5;
    protected javax.swing.JButton F1;
    protected javax.swing.JButton F2;
    protected javax.swing.JButton F3;
    protected javax.swing.JButton F4;
    protected javax.swing.JButton F5;
    private javax.swing.JLabel jBG;
    protected javax.swing.JButton jContinuar;
    private javax.swing.JLabel jDOTS;
    protected javax.swing.JButton jExit;
    private javax.swing.JPanel jLineas;
    // End of variables declaration//GEN-END:variables
    private int ordenclick;
    private int x, y;
}
