/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;
import java.awt.Graphics2D;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import javax.swing.*;
import java.awt.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author yenson
 */
/**
 *Clase principal de la interfaz
 */
public class InterfazDots extends javax.swing.JFrame {

    /**
     * Creates new form InterfazDots
     */
    public InterfazDots() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            clie= new Socket("Localhost",PUERTO);
        } catch (IOException ex) {
            Logger.getLogger(InterfazDots.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void linea (int x1, int y1, int x2, int y2){
    
        Graphics2D l = (Graphics2D)jLineas.getGraphics();
        BasicStroke Sl = new BasicStroke(9.0f, BasicStroke.CAP_SQUARE, BasicStroke.CAP_SQUARE);
        l.setStroke(Sl);
        l.setPaint(Color.BLUE);
        l.drawLine(x1, y1, x2, y2);
        
    }
    /**
     * Metodo para crear las figuras rellenas
     * @param x array de puntos x de las lineas pertenecientes a la figura
     * @param y array de puntos y de las lineas pertenecientes a la figura
     * @param n entero cantidad de puntos que conforman la figura
     */
    public void relleno (int x[], int y[], int n){
        Graphics2D r = (Graphics2D)jLineas.getGraphics();
        BasicStroke Sr = new BasicStroke(9.0f, BasicStroke.CAP_SQUARE, BasicStroke.CAP_SQUARE);
        r.setStroke(Sr);
        r.setPaint(Color.RED);
        r.fillPolygon(x, y, n);
    }
    /**
     * Metodo para enviar al servidor la linea nueva formada
     * @param b1 primer punto de la linea
     * @param b2 segundo punto de la linea
     */
    public void eServer(javax.swing.JButton b1, javax.swing.JButton b2){
        String boton1 = b1.getName();
        String boton2 = b2.getName();
        int indice = 0;
        puntosM[indice] = b1;
        indice +=1;
        puntosM[indice] = b2;
        int n11 = Character.getNumericValue(boton1.charAt(1));
        int n12 = Character.getNumericValue(boton1.charAt(2));
        int n21 = Character.getNumericValue(boton2.charAt(1));
        int n22 = Character.getNumericValue(boton2.charAt(2));
        String boton1S = "";
        String boton2S = "";
        boolean lineaValida = false;
        boolean reordenar = false;
        
        if (n11== n21){
            if(n12==n22+1){
                reordenar = true;
                lineaValida = true;
            }else if (n12+1==n22){
                reordenar = false;
                lineaValida = true;
            }
        } else if (n11== n21+1){
            if(n12==n22){
                reordenar = true;
                lineaValida = true;
            }else if(n12+1==n22){
                reordenar = true;
                lineaValida = true;
            }else if(n12==n22+1){
                reordenar = true;
                lineaValida = true;
            }
        } else if (n11+1== n21){
            if(n12==n22){
                reordenar = false;
                lineaValida = true;
            }else if(n12+1==n22){
                reordenar = false;
                lineaValida = true;
            }else if(n12==n22+1){
                reordenar = false;
                lineaValida = true;
            }
        }
        
        if (lineaValida){
            boton1S = Character.toString(boton1.charAt(0))+Character.toString(boton1.charAt(2));
            boton2S = Character.toString(boton2.charAt(0))+Character.toString(boton2.charAt(2));
            if(reordenar){
                puntos = boton2S + "," + boton1S;
            }else{
                puntos = boton1S + "," + boton2S;
            }
        }else{
            System.out.println("Por Favor ingrese una linea valida");
        }
        
        System.out.println("picha"+boton1S);
        System.out.println("picha"+boton2S);
    }  
    public void sendS(){
        try {
            DataOutputStream flujo= new DataOutputStream(clie.getOutputStream());
            flujo.writeUTF(puntos);

            System.out.println("por aqui va");

        }catch (IOException ex) {
            System.out.println("Error en la coneccion con el servidor");		
        }
    }
    public void receiveS(){
        String puntosN="";
        turno=true;
        
        try {
            while(turno==true) {
		System.out.println("RECIBIENDO");
		DataInputStream actualiz = new DataInputStream(clie.getInputStream());
		puntosN = actualiz.readUTF();
                System.out.println("cliente recibio"+ puntosN);
                turno=false;
	}
	}catch (Exception ex) {
            System.out.println("Error en la coneccion con el servidor");
	}
        
        if (puntosN.length()==5){
            String b1 = Character.toString(puntosN.charAt(0))+Character.toString(puntosN.charAt(1));
            String b2 = Character.toString(puntosN.charAt(3))+Character.toString(puntosN.charAt(4));
            if ("A".equals(Character.toString(b1.charAt(0)))){
                b1 = Character.toString(b1.charAt(0))+ "1"+ Character.toString(b1.charAt(1));
            }else if ("B".equals(Character.toString(b1.charAt(0)))){
                b1 = Character.toString(b1.charAt(0))+ "2"+ Character.toString(b1.charAt(1));
            }else if ("C".equals(Character.toString(b1.charAt(0)))){
                b1 = Character.toString(b1.charAt(0))+ "3"+ Character.toString(b1.charAt(1));
            }else if ("D".equals(Character.toString(b1.charAt(0)))){
                b1 = Character.toString(b1.charAt(0))+ "4"+ Character.toString(b1.charAt(1));
            }
            if ("A".equals(Character.toString(b2.charAt(0)))){
                b2 = Character.toString(b2.charAt(0))+ "1"+ Character.toString(b2.charAt(1));
            }else if ("B".equals(Character.toString(b2.charAt(0)))){
                b2 = Character.toString(b2.charAt(0))+ "2"+ Character.toString(b2.charAt(1));
            }else if ("C".equals(Character.toString(b2.charAt(0)))){
                b2 = Character.toString(b2.charAt(0))+ "3"+ Character.toString(b2.charAt(1));
            }else if ("D".equals(Character.toString(b2.charAt(0)))){
                b2 = Character.toString(b2.charAt(0))+ "4"+ Character.toString(b2.charAt(1));
            }   
            for (JButton b : puntosM){
                if (b.getName().equals(b1)){
                    bx=b.getX();
                    by=b.getY();
                }
                if (b.getName().equals(b2)){
                    linea(bx,by,b.getX(),b.getY());
                }
            }
        }else if(puntosN.length()>5){
            int indice2=0;
            for (int i=0;i<puntosN.length()-1;i++){
                if ("A".equals(Character.toString(puntosN.charAt(i)))){
                    puntosF[indice2] = Character.toString(puntosN.charAt(i))+ "1"+ Character.toString(puntosN.charAt(i+1));
                    indice2++;
                }else if ("B".equals(Character.toString(puntosN.charAt(i)))){
                    puntosF[indice2] = Character.toString(puntosN.charAt(i))+ "2"+ Character.toString(puntosN.charAt(i+1));
                    indice2++;
                }else if ("C".equals(Character.toString(puntosN.charAt(i)))){
                    puntosF[indice2] = Character.toString(puntosN.charAt(i))+ "3"+ Character.toString(puntosN.charAt(i+1));
                    indice2++;
                }else if ("D".equals(Character.toString(puntosN.charAt(i)))){
                    puntosF[indice2] = Character.toString(puntosN.charAt(i))+ "4"+ Character.toString(puntosN.charAt(i+1));
                    indice2++;
                }else{
                    i++;
                }
            }
            x = new int[puntosF.length];
            y = new int[puntosF.length];
            cantidadP = puntosF.length;
            for (String b : puntosF){
                for (JButton bn : puntosM){
                    if (bn.getName().equals(b)){
                        int ind=0;
                        x[ind] = bn.getX();
                        y[ind] = bn.getY();
                        ind++;
                }
            }
        }
        relleno(x,y,cantidadP);
        }  
    } 
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jExit = new javax.swing.JButton();
        jContinuar = new javax.swing.JButton();
        A11 = new javax.swing.JButton();
        A12 = new javax.swing.JButton();
        A13 = new javax.swing.JButton();
        A14 = new javax.swing.JButton();
        B21 = new javax.swing.JButton();
        B22 = new javax.swing.JButton();
        B23 = new javax.swing.JButton();
        B24 = new javax.swing.JButton();
        C31 = new javax.swing.JButton();
        C32 = new javax.swing.JButton();
        C33 = new javax.swing.JButton();
        C34 = new javax.swing.JButton();
        D41 = new javax.swing.JButton();
        D42 = new javax.swing.JButton();
        D43 = new javax.swing.JButton();
        D44 = new javax.swing.JButton();
        jLineas = new javax.swing.JPanel();
        jDOTS = new javax.swing.JLabel();
        jBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.darkGray);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jExit.setBackground(new java.awt.Color(254, 254, 254));
        jExit.setForeground(new java.awt.Color(80, 80, 80));
        jExit.setText("Salir");
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });
        getContentPane().add(jExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jContinuar.setBackground(new java.awt.Color(254, 254, 254));
        jContinuar.setForeground(new java.awt.Color(85, 85, 85));
        jContinuar.setText("Continuar");
        jContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(jContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        A11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        A11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A11.setBorderPainted(false);
        A11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A11MouseClicked(evt);
            }
        });
        A11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A11ActionPerformed(evt);
            }
        });
        getContentPane().add(A11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        A12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        A12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A12.setBorderPainted(false);
        A12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A12MouseClicked(evt);
            }
        });
        A12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A12ActionPerformed(evt);
            }
        });
        getContentPane().add(A12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        A13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        A13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A13.setBorderPainted(false);
        A13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A13MouseClicked(evt);
            }
        });
        A13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A13ActionPerformed(evt);
            }
        });
        getContentPane().add(A13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        A14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        A14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A14.setBorderPainted(false);
        A14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A14MouseClicked(evt);
            }
        });
        A14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A14ActionPerformed(evt);
            }
        });
        getContentPane().add(A14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        B21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        B21.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B21.setBorderPainted(false);
        B21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B21MouseClicked(evt);
            }
        });
        B21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B21ActionPerformed(evt);
            }
        });
        getContentPane().add(B21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        B22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        B22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B22.setBorderPainted(false);
        B22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B22MouseClicked(evt);
            }
        });
        getContentPane().add(B22, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        B23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        B23.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B23.setBorderPainted(false);
        B23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B23MouseClicked(evt);
            }
        });
        getContentPane().add(B23, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        B24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        B24.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B24.setBorderPainted(false);
        B24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B24MouseClicked(evt);
            }
        });
        getContentPane().add(B24, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));

        C31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        C31.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C31.setBorderPainted(false);
        C31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C31MouseClicked(evt);
            }
        });
        C31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C31ActionPerformed(evt);
            }
        });
        getContentPane().add(C31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        C32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        C32.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C32.setBorderPainted(false);
        C32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C32MouseClicked(evt);
            }
        });
        getContentPane().add(C32, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        C33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        C33.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C33.setBorderPainted(false);
        C33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C33MouseClicked(evt);
            }
        });
        getContentPane().add(C33, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        C34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        C34.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C34.setBorderPainted(false);
        C34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C34MouseClicked(evt);
            }
        });
        getContentPane().add(C34, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, -1));

        D41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        D41.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D41.setBorderPainted(false);
        D41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D41MouseClicked(evt);
            }
        });
        D41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D41ActionPerformed(evt);
            }
        });
        getContentPane().add(D41, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        D42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        D42.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D42.setBorderPainted(false);
        D42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D42MouseClicked(evt);
            }
        });
        getContentPane().add(D42, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, -1));

        D43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        D43.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D43.setBorderPainted(false);
        D43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D43MouseClicked(evt);
            }
        });
        getContentPane().add(D43, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, -1, -1));

        D44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dot.png"))); // NOI18N
        D44.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D44.setBorderPainted(false);
        D44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D44MouseClicked(evt);
            }
        });
        getContentPane().add(D44, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, -1, -1));

        jLineas.setOpaque(false);
        jLineas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLineas, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, 390, 450));

        jDOTS.setBackground(new java.awt.Color(252, 249, 246));
        jDOTS.setFont(new java.awt.Font("aakar", 1, 50)); // NOI18N
        jDOTS.setForeground(new java.awt.Color(72, 72, 72));
        jDOTS.setText("DOTS");
        getContentPane().add(jDOTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 140, -1));

        jBG.setBackground(new java.awt.Color(76, 76, 76));
        jBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bg_1.jpg"))); // NOI18N
        getContentPane().add(jBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jExitActionPerformed

    private void A13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A13ActionPerformed

    private void A14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A14ActionPerformed

    private void A12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A12ActionPerformed

    }//GEN-LAST:event_A12ActionPerformed

    private void A12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A12MouseClicked
        A12.setName("A12");
        if (ordenclick == 0){
            pI = A12;
            ordenclick+=1;
        }else{
            eServer(pI,A12);
            ordenclick-=1;
        }
    }//GEN-LAST:event_A12MouseClicked

    private void A13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A13MouseClicked
        A13.setName("A13");
        if (ordenclick == 0){
            pI = A13;
            ordenclick+=1;
        }else{
            eServer(pI,A13);
            ordenclick-=1;
        }
    }//GEN-LAST:event_A13MouseClicked

    private void A14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A14MouseClicked
        A14.setName("A14");
        if (ordenclick == 0){
            pI = A14;
            ordenclick+=1;
        }else{
            eServer(pI,A14);
            ordenclick-=1;
        }
    }//GEN-LAST:event_A14MouseClicked

    private void B21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B21MouseClicked
        B21.setName("B21");
        if (ordenclick == 0){
            pI = B21;
            ordenclick+=1;
        }else{
            eServer(pI,B21);
            ordenclick-=1;
        }
    }//GEN-LAST:event_B21MouseClicked

    private void B22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B22MouseClicked
        B22.setName("B22");
        if (ordenclick == 0){
            pI = B22;
            ordenclick+=1;
        }else{
            eServer(pI,B22);
            ordenclick-=1;
        }
    }//GEN-LAST:event_B22MouseClicked

    private void B23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B23MouseClicked
        B23.setName("B23");
        if (ordenclick == 0){
            pI = B23;
            ordenclick+=1;
        }else{
            eServer(pI,B23);
            ordenclick-=1;
        }
    }//GEN-LAST:event_B23MouseClicked

    private void B24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B24MouseClicked
        B24.setName("B24");
        if (ordenclick == 0){
            pI = B24;
            ordenclick+=1;
        }else{
            eServer(pI,B24);
            ordenclick-=1;
        }
    }//GEN-LAST:event_B24MouseClicked

    private void B21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B21ActionPerformed

    private void C31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C31MouseClicked
        C31.setName("C31");
        if (ordenclick == 0){
            pI = C31;
            ordenclick+=1;
        }else{
            eServer(pI,C31);
            ordenclick-=1;
        }
    }//GEN-LAST:event_C31MouseClicked

    private void C31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C31ActionPerformed

    private void C32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C32MouseClicked
        C32.setName("C32");
        if (ordenclick == 0){
            pI = C32;
            ordenclick+=1;
        }else{
            eServer(pI,C32);
            ordenclick-=1;
        }
    }//GEN-LAST:event_C32MouseClicked

    private void C33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C33MouseClicked
        C33.setName("C33");
        if (ordenclick == 0){
            pI = C33;
            ordenclick+=1;
        }else{
            eServer(pI,C33);
            ordenclick-=1;
        }
    }//GEN-LAST:event_C33MouseClicked

    private void C34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C34MouseClicked
        C34.setName("C34");
        if (ordenclick == 0){
            pI = C34;
            ordenclick+=1;
        }else{
            eServer(pI,C34);
            ordenclick-=1;
        }
    }//GEN-LAST:event_C34MouseClicked

    private void D41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D41MouseClicked
        D41.setName("D41");
        if (ordenclick == 0){
            pI = D41;
            ordenclick+=1;
        }else{
            eServer(pI,D41);
            ordenclick-=1;
        }
    }//GEN-LAST:event_D41MouseClicked

    private void D41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D41ActionPerformed

    private void D42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D42MouseClicked
        D42.setName("D42");
        if (ordenclick == 0){
            pI = D42;
            ordenclick+=1;
        }else{
            eServer(pI,D42);
            ordenclick-=1;
        }
    }//GEN-LAST:event_D42MouseClicked

    private void D43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D43MouseClicked
        D43.setName("D43");
        if (ordenclick == 0){
            pI = D43;
            ordenclick+=1;
        }else{
            eServer(pI,D43);
            ordenclick-=1;
        }
    }//GEN-LAST:event_D43MouseClicked

    private void D44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D44MouseClicked
        D44.setName("D44");
        if (ordenclick == 0){
            pI = D44;
            ordenclick+=1;
        }else{
            eServer(pI,D44);
            ordenclick-=1;
        }
    }//GEN-LAST:event_D44MouseClicked

    private void A11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A11MouseClicked
        A11.setName("A11");
        if (ordenclick == 0){
            pI = A11;
            ordenclick+=1;
        }else{
            ordenclick-=1;
            eServer(pI,A11);
        }
    }//GEN-LAST:event_A11MouseClicked

    private void A11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A11ActionPerformed

    }//GEN-LAST:event_A11ActionPerformed

    private void jContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jContinuarActionPerformed
        sendS();
        receiveS();

        
    }//GEN-LAST:event_jContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazDots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InterfazDots Interfaz = new InterfazDots();
                Interfaz.setVisible(true);
                
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton A11;
    protected javax.swing.JButton A12;
    protected javax.swing.JButton A13;
    protected javax.swing.JButton A14;
    protected javax.swing.JButton B21;
    protected javax.swing.JButton B22;
    protected javax.swing.JButton B23;
    protected javax.swing.JButton B24;
    protected javax.swing.JButton C31;
    protected javax.swing.JButton C32;
    protected javax.swing.JButton C33;
    protected javax.swing.JButton C34;
    protected javax.swing.JButton D41;
    protected javax.swing.JButton D42;
    protected javax.swing.JButton D43;
    protected javax.swing.JButton D44;
    private javax.swing.JLabel jBG;
    protected javax.swing.JButton jContinuar;
    private javax.swing.JLabel jDOTS;
    protected javax.swing.JButton jExit;
    private javax.swing.JPanel jLineas;
    // End of variables declaration//GEN-END:variables
    private int ordenclick;
    private javax.swing.JButton pI;
    private boolean turno = true;
    int PUERTO = 9666;
    private Socket clie;
    private String puntos = "";
    private javax.swing.JButton puntosM[]=new JButton [16];
    private int bx,by;
    private String puntosF[] = new String [50];
    private int x[];
    private int y[];
    private int cantidadP;
}
